#!/usr/bin/env node
// Environment requirements — a pack declares the toolchain a cloud session
// needs but the base image doesn't ship (see a pack's `env` field). Two
// dependency-free entry points, both driven by the repo's ACTIVE packs:
//
//   node env.mjs setup   Emit the aggregated environment-setup.sh for this
//                        repo's active packs — the script the user pastes into
//                        the Claude Code Web environment's "Setup script"
//                        field. It runs ONCE when the environment is created;
//                        Anthropic snapshots the filesystem, so later sessions
//                        already have the toolchain. Installs belong here, NOT
//                        in a per-session hook.
//
//   node env.mjs check   SessionStart assertion (web only): probe every active
//                        pack's requirement and the recorded version flag. If
//                        any is unmet, emit the halt-gate context telling the
//                        assistant to alert the user; silent when satisfied.
//                        It only ASSERTS — it never installs.
//
// A pack's declaration:
//   env: {
//     label: 'Flutter SDK',                         // human name for messages
//     version: 1,                                   // bump on any setup change
//     setup: '<bash>',                              // idempotent install fragment
//     probe: 'command -v flutter >/dev/null 2>&1',  // exit 0 iff present
//   }
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { loadPacks, isActive } from './registry.mjs';

// Where environment-setup.sh records the version it installed, and the check
// reads it back. Outside the repo so the snapshot (not the checkout) carries it.
export const FLAG_PATH = '/opt/claude-env/setup-version';

/** The `env` declarations of a repo's active packs (universal + declared). */
export async function activeEnvs(projectRoot, packs) {
  let declared = [];
  const configPath = join(projectRoot, '.claudinite-checks.json');
  if (existsSync(configPath)) {
    try {
      const raw = JSON.parse(readFileSync(configPath, 'utf8'));
      if (Array.isArray(raw.packs)) declared = raw.packs;
    } catch {
      /* an unparsable config declares nothing extra — universal still applies */
    }
  }
  packs ??= await loadPacks();
  return packs
    .filter((p) => p.env && isActive(p, { packs: declared }))
    .map((p) => ({ id: p.id, ...p.env }));
}

/** Combined version — any change to an active pack's env (id/version) invalidates. */
export function aggregateVersion(envs) {
  const basis = envs.map((e) => `${e.id}:${e.version ?? 0}`).sort().join('|');
  return createHash('sha256').update(basis).digest('hex').slice(0, 12);
}

/** The environment-setup.sh body for these env declarations (generated artifact). */
export function emitSetup(envs) {
  const out = [
    '#!/bin/bash',
    '# GENERATED by Claudinite (packs/env.mjs setup) — do not hand-edit.',
    '# Paste the FULL contents into the Claude Code Web environment\'s "Setup',
    '# script" field (environment settings). It runs once when the environment is',
    '# created; the filesystem is snapshotted, so later sessions already have',
    '# these prerequisites. Regenerate after an active pack changes:',
    '#   node .claudinite/packs/env.mjs setup > .claude/environment-setup.sh',
    'set -euo pipefail',
    '',
  ];
  if (!envs.length) {
    out.push('# No active pack declares an environment requirement.', '');
  }
  for (const e of envs) {
    out.push(`# --- ${e.label || e.id} (pack: ${e.id}) ---`, e.setup.trim(), '');
  }
  out.push(
    '# --- Claudinite environment version flag (validated at session start) ---',
    'mkdir -p "$(dirname "' + FLAG_PATH + '")"',
    `echo "${aggregateVersion(envs)}" > ${FLAG_PATH}`,
    ''
  );
  return out.join('\n');
}

/**
 * Pure decision: which requirements are unmet. `probe(env) -> bool` reports
 * whether a requirement is present; `actualFlag` is the recorded version (or
 * null). Returns human-readable problems, empty when the environment is good.
 */
export function evaluate(envs, { probe, actualFlag }) {
  const problems = [];
  for (const e of envs) {
    if (!probe(e)) problems.push(`${e.label || e.id} is not installed`);
  }
  if (!problems.length && envs.length) {
    const expected = aggregateVersion(envs);
    if (actualFlag == null || actualFlag === '') {
      problems.push('the environment setup script has not been applied (no version flag on disk)');
    } else if (actualFlag !== expected) {
      problems.push(`the environment setup script is out of date (environment is ${actualFlag}, packs expect ${expected})`);
    }
  }
  return problems;
}

function emitAlert(problems) {
  const msg =
    `Environment setup check failed: ${problems.join('; ')}. Alert the user: regenerate ` +
    '.claude/environment-setup.sh with (node .claudinite/packs/env.mjs setup > .claude/environment-setup.sh), ' +
    'copy its full contents into the Claude Code Web environment Setup script field, then start a fresh ' +
    'session so the snapshot rebuilds with the prerequisites installed.';
  process.stdout.write(
    `${JSON.stringify({ hookSpecificOutput: { hookEventName: 'SessionStart', additionalContext: msg } })}\n`
  );
}

async function check(projectRoot) {
  // Web only — locally the developer installs toolchains directly.
  if (process.env.CLAUDE_CODE_REMOTE !== 'true') return;
  const envs = await activeEnvs(projectRoot);
  if (!envs.length) return;
  let actualFlag = null;
  try { actualFlag = readFileSync(FLAG_PATH, 'utf8').trim(); } catch { /* not applied */ }
  const problems = evaluate(envs, {
    probe: (e) => spawnSync('bash', ['-c', e.probe], { encoding: 'utf8' }).status === 0,
    actualFlag,
  });
  if (problems.length) emitAlert(problems);
}

// CLI — but importable (the tests import the pure helpers above).
if (import.meta.url === pathToFileURL(process.argv[1] || '').href) {
  const cmd = process.argv[2];
  const projectRoot = process.env.CLAUDE_PROJECT_DIR || process.cwd();
  if (cmd === 'setup') {
    process.stdout.write(emitSetup(await activeEnvs(projectRoot)));
  } else if (cmd === 'check') {
    await check(projectRoot); // fails soft — a SessionStart hook must never crash the session
  } else {
    process.stderr.write('usage: env.mjs <setup|check>\n');
    process.exit(2);
  }
}
