import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { badgeSvg, stripSvg, packBadge, packBadges, renderAll } from '../../engine/badges/render.mjs';

// The badge files are checked in — a README loads its artwork over HTTP, so it
// has to exist as a file — which makes every one of them a copy of something
// its pack's manifest already says. This is the drift guard that copy needs:
// re-render everything and compare byte-for-byte, so a manifest edited without
// a regenerate fails here rather than shipping a mark that no longer matches
// its declaration. (It is also why the files can keep the plain `badge.svg`
// name a consumer pastes into a README, instead of the GENERATED-in-the-filename
// convention that would otherwise be carrying this weight.)

const REPO = fileURLToPath(new URL('../..', import.meta.url));

// Where this repo's own usage strip is written — the one path the generator
// takes as an argument rather than deriving, so the test that regenerates it and
// the README that displays it must agree. Both halves are asserted below.
const STRIP = 'docs/pack-usage.svg';

const tracked = () => new Set(execFileSync('git', ['ls-files'], { cwd: REPO, encoding: 'utf8' }).split('\n').filter(Boolean));

async function rendered() {
  const { files, errors } = await renderAll({ stripPath: STRIP, declared: JSON.parse(readFileSync(join(REPO, '.claudinite-checks.json'), 'utf8')).packs });
  return { files, errors };
}

test('every pack declares a usable badge', async () => {
  const { errors } = await packBadges({ localRoot: REPO });
  assert.deepEqual(errors.map((e) => e.what), [], 'a pack is missing its badge declaration — add badge: { file, color, glyph } to its pack.mjs');
});

test('every checked-in badge matches what its manifest renders', async () => {
  const { files, errors } = await rendered();
  assert.deepEqual(errors, []);
  const stale = [];
  for (const [rel, content] of files) {
    const path = join(REPO, rel);
    if (!existsSync(path) || readFileSync(path, 'utf8') !== content) stale.push(rel);
  }
  assert.deepEqual(stale, [], `these files disagree with the manifests that generate them — re-run \`node engine/badges/render.mjs ${STRIP}\``);
});

test('every rendered badge is tracked, so it vendors with its pack', async () => {
  const { files } = await rendered();
  const known = tracked();
  const untracked = [...files.keys()].filter((f) => !known.has(f));
  assert.deepEqual(untracked, [], 'a badge that git does not track ships to no consumer — git add it');
});

test("the README displays the strip the generator writes", () => {
  const readme = readFileSync(join(REPO, 'README.md'), 'utf8');
  assert.match(readme, new RegExp(`!\\[[^\\]]+\\]\\(${STRIP.replace(/[.]/g, '\\.')}[\\s)]`), `README.md no longer shows ${STRIP} as an image — the strip and the page that displays it have drifted apart`);
});

// --- the renderers themselves, on a synthetic pack -------------------------

const FAKE = { id: 'demo-pack', dir: '/x/packs/demo-pack', file: 'badge.svg', color: '#102030', glyph: 'M8 8h16' };

test('a badge is a self-contained 32px tile with the declared color and glyph', () => {
  const svg = badgeSvg(FAKE, { source: 'packs/demo-pack/pack.mjs' });
  assert.match(svg, /viewBox="0 0 32 32" width="32" height="32"/);
  assert.match(svg, /stop-color="#102030"/);
  assert.match(svg, /d="M8 8h16"/);
  assert.match(svg, /GENERATED by engine\/badges\/render\.mjs from packs\/demo-pack\/pack\.mjs/);
  // The darkened stop is derived from the declared color, never declared beside it.
  assert.match(svg, /stop-color="#0c1925"/);
});

test('a strip lays its tiles out in one row, gap included', () => {
  const svg = stripSvg([FAKE, { ...FAKE, id: 'other-pack' }], { source: 'x' });
  assert.match(svg, /viewBox="0 0 72 32" width="72" height="32"/); // 32 + 8 + 32
  assert.match(svg, /transform="translate\(40 0\)"/);
  // Gradient ids are namespaced, or the second tile would paint with the first's fill.
  assert.match(svg, /id="b-demo-pack"/);
  assert.match(svg, /id="b-other-pack"/);
});

test('an empty declaration renders an empty strip rather than a broken one', () => {
  assert.match(stripSvg([], { source: 'x' }), /viewBox="0 0 0 32"/);
});

test('a malformed badge declaration is reported, not rendered', () => {
  assert.deepEqual(packBadge({ id: 'p', dir: '/x' }).spec, null);
  assert.deepEqual(packBadge({ id: 'p', dir: '/x', badge: { file: 'badge.svg', color: 'blue', glyph: 'M0 0' } }).spec, null);
  assert.deepEqual(packBadge({ id: 'p', dir: '/x', badge: { file: '../../etc/x', color: '#ffffff', glyph: 'M0 0' } }).spec, null);
  assert.equal(packBadge({ id: 'p', dir: '/x', badge: { file: 'badge.svg', color: '#ffffff', glyph: 'M0 0' } }).spec.id, 'p');
});
